import { INoteRepository } from "../../domain/repositories/INoteRepository";
import { Note } from "../../domain/entities/Note";

export class CreateNoteService {
  constructor(private noteRepository: INoteRepository) {}

  async execute(data: {
    title: string;
    content: string;
    userId: number;
  }): Promise<Note> {
    // The note ID can be generated by the repository or here using a UUID library.
    const newNote = new Note(
      data.title,
      data.content,
      data.userId,
      new Date(),
      new Date()
    );
    return this.noteRepository.create(newNote);
  }
}
