import { IUserRepository } from "../../domain/repositories/IUserRepository";
import { User } from "../../domain/entities/User";

export class CreateUserService {
  constructor(private userRepository: IUserRepository) {}

  async execute(data: {
    id: number;
    name: string;
    cognitoId: string;
  }): Promise<User> {
    // The note ID can be generated by the repository or here using a UUID library.
    const newUser = new User(
      data.id,
      data.name,
      data.cognitoId,
      new Date(),
      new Date()
    );
    return this.userRepository.create(newUser);
  }
}
