import { INoteRepository } from "../../domain/repositories/INoteRepository";
import { Note } from "../../domain/entities/Note";

export class EditNoteService {
  constructor(private noteRepository: INoteRepository) {}

  async execute(data: {
    noteId: number;
    title: string;
    content: string;
    userId: number;
    createdAt: Date;
  }): Promise<Note> {
    // The note ID can be generated by the repository or here using a UUID library.
    const updatedNote = new Note(
      data.title,
      data.content,
      data.userId,
      data.createdAt,
      new Date(),
      data.noteId
    );
    return this.noteRepository.update(updatedNote);
  }
}
